version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - restore_cache: 
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run seed:test
      - run: npm run mocha
      - run: npm run test


      
